name: local-library
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATA_DIR=/data
      - DB_DIR=/db
      - COVERS_DIR=/covers
    ports:
      - 8000:8000
    volumes:
      - /home/leo/local-library/data:/data:ro
      - db:/db:rw
      - covers:/covers:rw
    networks:
      - local-library
  
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 4321:4321
    volumes:
      - covers:/app/public/covers:ro
    networks:
      - local-library

volumes:
  db: {}
  covers: {}
networks:
  local-library:
    driver: bridge